# Generated by Django 4.2.3 on 2023-07-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.IntegerField()),
                ('blood_group', models.TextField(max_length=3)),
                ('Father_name', models.CharField(max_length=255)),
                ('physically_challenged', models.CharField(max_length=3)),
                ('Religion', models.CharField(max_length=255)),
                ('Graduation', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subemployee', to='employee.employee_model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
